import { MetadataRoute } from 'next';
import { siteConfig } from '@/lib/seo';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/dashboard/',
          '/auth/',
          '/profile/edit/',
          '/profile/settings/',
          '/profile/notifications/',
          '/wallet/',
          '/email/unsubscribe/',
          // SEO Strategy: Never index wallet actions, create/edit flows, private deals
          '/projects/create/',
          '/projects/*/edit',
          '/campaigns/create/',
          '/campaigns/*/edit',
          '/deals/create/',
          '/deals/*/edit',
          '/projects?*',
          '/campaigns?*',
          '/deals?*',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/dashboard/',
          '/auth/',
          '/profile/edit/',
          '/profile/settings/',
          '/profile/notifications/',
          '/wallet/',
          '/email/unsubscribe/',
          '/projects/create/',
          '/projects/*/edit',
          '/campaigns/create/',
          '/campaigns/*/edit',
          '/deals/create/',
          '/deals/*/edit',
          '/projects?*',
          '/campaigns?*',
          '/deals?*',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/dashboard/',
          '/auth/',
          '/profile/edit/',
          '/profile/settings/',
          '/profile/notifications/',
          '/wallet/',
          '/email/unsubscribe/',
          '/projects/create/',
          '/projects/*/edit',
          '/campaigns/create/',
          '/campaigns/*/edit',
          '/deals/create/',
          '/deals/*/edit',
          '/projects?*',
          '/campaigns?*',
          '/deals?*',
        ],
      },
    ],
    sitemap: `${siteConfig.url}/sitemap.xml`,
  };
}

